<?php
/**
 * @author Mattia Corvaglia <corvagliamattia@gmail.com>
 * @link http://mattiacorvaglia.com
 */

require_once "../handlers/db_manager.php";

class Bar {

  // ---------------------------------------------------------------------------
  public function read() {
    // Connect database
    $conn = db_connect();

    // Retrieve all the rows
    $query = 'SELECT `id_bar`,`name`,`comment` FROM `foo`.`bar`;';
    $res = mysqli_query($conn, $query);

    // Check invalid query
    if (!$res) {
      $result = array(
        'error_code' => 16,
        'error_desc' => 'Invalid query: '.$query
      );
      mysqli_close($conn);
      return $result;
    }

    // Extract the results into an associative array
    $rows = array();
    if (mysqli_num_rows($res) > 0) {
      while ($row = mysqli_fetch_array($res, MYSQLI_ASSOC)) {
        array_push($rows, $row);
      }
    }

    // Close database connection
    mysqli_free_result($res);
    mysqli_close($conn);

    // Return the results
    return $rows;
  }
  // ---------------------------------------------------------------------------
  public function get($id) {
    // Connect database
    $conn = db_connect();

    // Retrieve the row by id
    $query = 'SELECT `id_bar`,`name`,`comment` FROM `foo`.`bar` WHERE `id_bar`='.$id.';';
    $res = mysqli_query($conn, $query);

    // Check invalid query
    if (!$res) {
      $result = array(
        'error_code' => 16,
        'error_desc' => 'Invalid query: '.$query
      );
      mysqli_close($conn);
      return $result;
    }

    // Extract the result into an associative array
    $row = mysqli_fetch_array($res, MYSQLI_ASSOC);

    // Close database connection
    mysqli_free_result($res);
    mysqli_close($conn);

    // Return the result
    return $row;
  }
  // ---------------------------------------------------------------------------
  public function create($data) {
    // Connect database
    $conn = db_connect();

    // Insert a new row
    $query = 'INSERT INTO `foo`.`bar` (`name`,`comment`) VALUES (\''.$data['name'].'\',\''.$data['comment'].'\');';
    $res = mysqli_query($conn, $query);

    // Check invalid query
    if (!$res) {
      $result = array(
        'error_code' => 16,
        'error_desc' => 'Invalid query: '.$query
      );
      mysqli_close($conn);
      return $result;
    }

    // Get the autogenerated id
    $newId = mysqli_insert_id($conn);
    $data['id_bar'] = $newId;

    // Close database connection
    mysqli_close($conn);

    // Return the result
    return $data;
  }
  // ---------------------------------------------------------------------------
  public function update($id, $data) {
    // Connect database
    $conn = db_connect();

    // Insert a new row
    $query = 'UPDATE `foo`.`bar` SET `name`=\''.$data['name'].'\',`comment`=\''.$data['comment'].'\' WHERE `id_bar`='.$id.';';
    $res = mysqli_query($conn, $query);

    // Check invalid query
    if (!$res) {
      $result = array(
        'error_code' => 16,
        'error_desc' => 'Invalid query: '.$query
      );
      mysqli_close($conn);
      return $result;
    }

    // Check the result
    if (mysqli_affected_rows($conn) < 1) {
      $result = array(
        'error_code' => 15,
        'error_desc' => 'Impossible to update the record in the database. Query: '.$query
      );
      mysqli_close($conn);
      return $result;
    }

    // Close database connection
    mysqli_close($conn);

    // Return the result
    $data['id_bar'] = $id;
    return $data;
  }
  // ---------------------------------------------------------------------------
  public function delete($id) {
    // Connect database
    $conn = db_connect();

    // Insert a new row
    $query = 'DELETE FROM `foo`.`bar` WHERE `id_bar`='.$id.';';
    $res = mysqli_query($conn, $query);

    // Check invalid query
    if (!$res) {
      $result = array(
        'error_code' => 16,
        'error_desc' => 'Invalid query: '.$query
      );
      mysqli_close($conn);
      return $result;
    }

    // Check the result
    if (mysqli_affected_rows($conn) < 1) {
      $result = array('deleted' => false);
      mysqli_close($conn);
      return $result;
    }

    // Close database connection
    mysqli_close($conn);

    // Return the result
    $result = array('deleted' => true);
    return $result;
  }

}

?>
